FROM webdevops/php:8.2-alpine

RUN apk add oniguruma-dev postgresql-dev libxml2-dev
RUN docker-php-ext-install bcmath ctype fileinfo mbstring pdo_pgsql xml

WORKDIR /var/www/html

RUN chown -R application:application .
